name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync-with-huggingface.yml
      - examples/github_runner_app/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@c1518d9edf69c7e6beaa8f0c35df06d5952e2cf0  # v0.0.4
      with:
        github_repo_id: huggingface/fuego
        huggingface_repo_id: nateraw/fuego
        repo_type: space
        space_sdk: gradio
        subdirectory: examples/github_runner_app
        hf_token: ${{ secrets.HF_TOKEN }}
